package com.zeal.softwareengineeringprojectmanage.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StagetopicresultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public StagetopicresultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStagetopicidIsNull() {
            addCriterion("stagetopicId is null");
            return (Criteria) this;
        }

        public Criteria andStagetopicidIsNotNull() {
            addCriterion("stagetopicId is not null");
            return (Criteria) this;
        }

        public Criteria andStagetopicidEqualTo(Integer value) {
            addCriterion("stagetopicId =", value, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidNotEqualTo(Integer value) {
            addCriterion("stagetopicId <>", value, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidGreaterThan(Integer value) {
            addCriterion("stagetopicId >", value, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidGreaterThanOrEqualTo(Integer value) {
            addCriterion("stagetopicId >=", value, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidLessThan(Integer value) {
            addCriterion("stagetopicId <", value, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidLessThanOrEqualTo(Integer value) {
            addCriterion("stagetopicId <=", value, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidIn(List<Integer> values) {
            addCriterion("stagetopicId in", values, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidNotIn(List<Integer> values) {
            addCriterion("stagetopicId not in", values, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidBetween(Integer value1, Integer value2) {
            addCriterion("stagetopicId between", value1, value2, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andStagetopicidNotBetween(Integer value1, Integer value2) {
            addCriterion("stagetopicId not between", value1, value2, "stagetopicid");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkIsNull() {
            addCriterion("downloadlink is null");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkIsNotNull() {
            addCriterion("downloadlink is not null");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkEqualTo(String value) {
            addCriterion("downloadlink =", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkNotEqualTo(String value) {
            addCriterion("downloadlink <>", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkGreaterThan(String value) {
            addCriterion("downloadlink >", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkGreaterThanOrEqualTo(String value) {
            addCriterion("downloadlink >=", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkLessThan(String value) {
            addCriterion("downloadlink <", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkLessThanOrEqualTo(String value) {
            addCriterion("downloadlink <=", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkLike(String value) {
            addCriterion("downloadlink like", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkNotLike(String value) {
            addCriterion("downloadlink not like", value, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkIn(List<String> values) {
            addCriterion("downloadlink in", values, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkNotIn(List<String> values) {
            addCriterion("downloadlink not in", values, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkBetween(String value1, String value2) {
            addCriterion("downloadlink between", value1, value2, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andDownloadlinkNotBetween(String value1, String value2) {
            addCriterion("downloadlink not between", value1, value2, "downloadlink");
            return (Criteria) this;
        }

        public Criteria andIspassIsNull() {
            addCriterion("isPass is null");
            return (Criteria) this;
        }

        public Criteria andIspassIsNotNull() {
            addCriterion("isPass is not null");
            return (Criteria) this;
        }

        public Criteria andIspassEqualTo(Byte value) {
            addCriterion("isPass =", value, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassNotEqualTo(Byte value) {
            addCriterion("isPass <>", value, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassGreaterThan(Byte value) {
            addCriterion("isPass >", value, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassGreaterThanOrEqualTo(Byte value) {
            addCriterion("isPass >=", value, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassLessThan(Byte value) {
            addCriterion("isPass <", value, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassLessThanOrEqualTo(Byte value) {
            addCriterion("isPass <=", value, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassIn(List<Byte> values) {
            addCriterion("isPass in", values, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassNotIn(List<Byte> values) {
            addCriterion("isPass not in", values, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassBetween(Byte value1, Byte value2) {
            addCriterion("isPass between", value1, value2, "ispass");
            return (Criteria) this;
        }

        public Criteria andIspassNotBetween(Byte value1, Byte value2) {
            addCriterion("isPass not between", value1, value2, "ispass");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNull() {
            addCriterion("suggestion is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionIsNotNull() {
            addCriterion("suggestion is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionEqualTo(String value) {
            addCriterion("suggestion =", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotEqualTo(String value) {
            addCriterion("suggestion <>", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThan(String value) {
            addCriterion("suggestion >", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion >=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThan(String value) {
            addCriterion("suggestion <", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLessThanOrEqualTo(String value) {
            addCriterion("suggestion <=", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionLike(String value) {
            addCriterion("suggestion like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotLike(String value) {
            addCriterion("suggestion not like", value, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionIn(List<String> values) {
            addCriterion("suggestion in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotIn(List<String> values) {
            addCriterion("suggestion not in", values, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionBetween(String value1, String value2) {
            addCriterion("suggestion between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSuggestionNotBetween(String value1, String value2) {
            addCriterion("suggestion not between", value1, value2, "suggestion");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIsNull() {
            addCriterion("submittime is null");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIsNotNull() {
            addCriterion("submittime is not null");
            return (Criteria) this;
        }

        public Criteria andSubmittimeEqualTo(Date value) {
            addCriterion("submittime =", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotEqualTo(Date value) {
            addCriterion("submittime <>", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeGreaterThan(Date value) {
            addCriterion("submittime >", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeGreaterThanOrEqualTo(Date value) {
            addCriterion("submittime >=", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeLessThan(Date value) {
            addCriterion("submittime <", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeLessThanOrEqualTo(Date value) {
            addCriterion("submittime <=", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIn(List<Date> values) {
            addCriterion("submittime in", values, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotIn(List<Date> values) {
            addCriterion("submittime not in", values, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeBetween(Date value1, Date value2) {
            addCriterion("submittime between", value1, value2, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotBetween(Date value1, Date value2) {
            addCriterion("submittime not between", value1, value2, "submittime");
            return (Criteria) this;
        }

        public Criteria andTopicidIsNull() {
            addCriterion("topicId is null");
            return (Criteria) this;
        }

        public Criteria andTopicidIsNotNull() {
            addCriterion("topicId is not null");
            return (Criteria) this;
        }

        public Criteria andTopicidEqualTo(Integer value) {
            addCriterion("topicId =", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotEqualTo(Integer value) {
            addCriterion("topicId <>", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidGreaterThan(Integer value) {
            addCriterion("topicId >", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidGreaterThanOrEqualTo(Integer value) {
            addCriterion("topicId >=", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLessThan(Integer value) {
            addCriterion("topicId <", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidLessThanOrEqualTo(Integer value) {
            addCriterion("topicId <=", value, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidIn(List<Integer> values) {
            addCriterion("topicId in", values, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotIn(List<Integer> values) {
            addCriterion("topicId not in", values, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidBetween(Integer value1, Integer value2) {
            addCriterion("topicId between", value1, value2, "topicid");
            return (Criteria) this;
        }

        public Criteria andTopicidNotBetween(Integer value1, Integer value2) {
            addCriterion("topicId not between", value1, value2, "topicid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stagetopicresult
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}