package com.zeal.softwareengineeringprojectmanage.bean;

import java.io.Serializable;
import java.util.Date;

public class Stagetopicresult implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagetopicresult.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagetopicresult.stagetopicId
     *
     * @mbggenerated
     */
    private Integer stagetopicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagetopicresult.downloadlink
     *
     * @mbggenerated
     */
    private String downloadlink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagetopicresult.isPass
     *
     * @mbggenerated
     */
    private Byte ispass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagetopicresult.suggestion
     *
     * @mbggenerated
     */
    private String suggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagetopicresult.submittime
     *
     * @mbggenerated
     */
    private Date submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagetopicresult.topicId
     *
     * @mbggenerated
     */
    private Integer topicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagetopicresult.id
     *
     * @return the value of stagetopicresult.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagetopicresult.id
     *
     * @param id the value for stagetopicresult.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagetopicresult.stagetopicId
     *
     * @return the value of stagetopicresult.stagetopicId
     *
     * @mbggenerated
     */
    public Integer getStagetopicid() {
        return stagetopicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagetopicresult.stagetopicId
     *
     * @param stagetopicid the value for stagetopicresult.stagetopicId
     *
     * @mbggenerated
     */
    public void setStagetopicid(Integer stagetopicid) {
        this.stagetopicid = stagetopicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagetopicresult.downloadlink
     *
     * @return the value of stagetopicresult.downloadlink
     *
     * @mbggenerated
     */
    public String getDownloadlink() {
        return downloadlink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagetopicresult.downloadlink
     *
     * @param downloadlink the value for stagetopicresult.downloadlink
     *
     * @mbggenerated
     */
    public void setDownloadlink(String downloadlink) {
        this.downloadlink = downloadlink == null ? null : downloadlink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagetopicresult.isPass
     *
     * @return the value of stagetopicresult.isPass
     *
     * @mbggenerated
     */
    public Byte getIspass() {
        return ispass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagetopicresult.isPass
     *
     * @param ispass the value for stagetopicresult.isPass
     *
     * @mbggenerated
     */
    public void setIspass(Byte ispass) {
        this.ispass = ispass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagetopicresult.suggestion
     *
     * @return the value of stagetopicresult.suggestion
     *
     * @mbggenerated
     */
    public String getSuggestion() {
        return suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagetopicresult.suggestion
     *
     * @param suggestion the value for stagetopicresult.suggestion
     *
     * @mbggenerated
     */
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion == null ? null : suggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagetopicresult.submittime
     *
     * @return the value of stagetopicresult.submittime
     *
     * @mbggenerated
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagetopicresult.submittime
     *
     * @param submittime the value for stagetopicresult.submittime
     *
     * @mbggenerated
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagetopicresult.topicId
     *
     * @return the value of stagetopicresult.topicId
     *
     * @mbggenerated
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagetopicresult.topicId
     *
     * @param topicid the value for stagetopicresult.topicId
     *
     * @mbggenerated
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagetopicresult
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", stagetopicid=").append(stagetopicid);
        sb.append(", downloadlink=").append(downloadlink);
        sb.append(", ispass=").append(ispass);
        sb.append(", suggestion=").append(suggestion);
        sb.append(", submittime=").append(submittime);
        sb.append(", topicid=").append(topicid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}